# Today we learn about Python

In [3]:
print(True)
print(False)
x=None
print(x)

print(...)

def add(a, b):
    return NotImplemented

print(__debug__)    



True
False
None
Ellipsis
True


In [ ]:
# whata is ellipsis?
# used for placeholders, e.g. in function definitions or type hints ,,, advanced slicing

# mean something is missing so we used ... here i used python ellipsis object

In [ ]:
import numpy as np
arr=np.arange(27).reshape(3,3,3)
print(arr)
print("-----------------------------")




[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]
-----------------------------


In [11]:
print(arr[:,:,0],'\n')
print(arr[...,0],'\n')  # using ellipsis to select all elements in the last dimension
print(arr[...,1],'\n')  # using ellipsis to select all elements in the last dimension

[[ 0  3  6]
 [ 9 12 15]
 [18 21 24]] 

[[ 0  3  6]
 [ 9 12 15]
 [18 21 24]] 

[[ 1  4  7]
 [10 13 16]
 [19 22 25]] 



In [18]:
print(arr,'\n\n')
# filter only first row of each one
print('======================================')
print(arr[:, 0, ...])


[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]] 


[[ 0  1  2]
 [ 9 10 11]
 [18 19 20]]


In [19]:
print(arr[0,...],'\n')  # using ellipsis to select all elements in the last dimension

[[0 1 2]
 [3 4 5]
 [6 7 8]] 



In [20]:
print(...)

Ellipsis


In [30]:
# concept of type Hint


def greet(name: str) -> str:
    return f"Hello, {name}!"


print(greet("Adeel"))
print(greet(123))


def add_numbers(a: int, b: int) -> int:
    return a + b

print(add_numbers(5, 10))
print(add_numbers("Num", "Adeel"))  



Hello, Adeel!
Hello, 123!
15
NumAdeel


In [ ]:
#  use ellipse in callable 

from typing import Callable
def call_back_fun(f: Callable[...,int]):
    result=f('hello',7,False)
    print('call_back_fun print : ',result)

def sample_function(a,b,c):
    return 42    

a=call_back_fun(sample_function)
print("what a is print",a)


call_back_fun print :  42
None


In [ ]:
# use ellipsis in get item method of a class
class MyClass:
    def __getitem__(self, item):
        if item is ...:  # Check for ellipsis
            return "You used ellipsis!"
        return f"You accessed item: {item}"
    
    

In [42]:
# not implemented example
class MyNotImplementedClass:
    def my_method(self):
        return NotImplemented



# Example of NotImplemented in equality checks


class A:
    def __eq__(self,other):
        if isinstance(other, B):
            return False
        return NotImplemented

class B:
    def __eq__(self, other):
        if isinstance(other, A):
            return True
        return NotImplemented

a=A()
b=B()
print(a == b)  # This will return NotImplemented


False


In [40]:
print(b == a)  # This will return False, as B's __eq__ method returns False for A        

False


In [43]:

class Teacher:
    def __eq__(self, other):
        if isinstance(other, Student):
            return False  # Teachers are not equal to students
        return NotImplemented

class Student:
    def __eq__(self, other):
        if isinstance(other, Teacher):
            return True  # Students respect teachers and say they're equal 😄
        return NotImplemented

t = Teacher()
s = Student()

print(t == s)  # Output: False
print(s == t)  # Output: True


False
True


In [44]:
class A:
    def __eq__(self, other):
        return NotImplemented  

class B:
    def __eq__(self, other):
        if isinstance(other, A):
            return True  
        return NotImplemented

a = A()
b = B()

print(a == b)  # Output: True


True


In [45]:
class A:
    def __eq__(self, other):
        return NotImplemented  

class B:
    def __eq__(self, other):
        return NotImplemented  

a = A()
b = B()

print(a == b)  # Output: False


False


In [ ]:
class A:
    def __eq__(self, other):
        if isinstance(other, B):
            return False  
        return NotImplemented

class B:
    def __eq__(self, other):
        return NotImplemented  

a = A()
b = B()

print(a == b)  # Output: False


False


In [48]:
import random
from typing import Callable, List

# Step 1: Dice Roller
def roll_dice() -> int:
    return random.randint(1, 6)

# Step 2: Luck Tester
def test_your_luck(callback: Callable[..., int], N: int) -> List[int]:
    results = []
    for _ in range(N):
        results.append(callback())  # Roll dice N times
    return results

# Example Usage
luck_results = test_your_luck(roll_dice, 2)
print(luck_results)  # e.g., [4, 1, 6]

[1, 1]


In [49]:
class Robot:
    def __eq__(self, other):
        if isinstance(other, Human):
            return NotImplemented  # "I don't know—ask the Human!"
        return super().__eq__(other)  # Default behavior (not needed here)

class Human:
    def __eq__(self, other):
        if isinstance(other, Robot):
            return True  # Humans always say robots are equal!
        return super().__eq__(other)

# Test
robot = Robot()
human = Human()

print(robot == human)  # Output: True (Python asks Human.__eq__)
print(human == robot)  # Output: True (Human.__eq__ says yes)

True
True


In [ ]:
# what is static accessor
# two types of accessors in python
# static methodes (me actually not doing anything)
# class methods (me actually doing something) ko class k bare me pataho hai
# 
# 
class StaticAccessor:
    @staticmethod
    def static_method():
        return "This is a static method!"

In [ ]:
class Example:
    company="systrem"
    
    # regular accesser
    def instance_methode(self):
        print('i am instaance methode')
        print(self.company)
    # class accesor 
    @classmethod
    def class_method(cls):
        print(f"i am a class method.my class is {cls}") 
        print(cls.company)
    # static accessors   
    @staticmethod
    def static_method():
        print("i am a static methode. i don't know how to class or object.")  
        # print(self.company)  


e = Example()
e.instance_methode()
e.class_method()
e.static_method()        

i am instaance methode
systrem
i am a class method.my class is <class '__main__.Example'>
systrem
i am a static methode. i don't know how to class or object.


NameError: name 'self' is not defined

In [58]:
# use case static methodes

'''
1)


'''

import math
class geometry:
    @staticmethod
    def area_of_circle(radius):
        return math.pi * radius ** 2
print(geometry.area_of_circle(5))

78.53981633974483


In [ ]:
# class method

# factory method
'''
factory methde is a class method that create a object in 
'''




TypeError: Door() takes no arguments

In [65]:
class Door:
    def __init__(self, color, width):  # Fixed: Double underscores
        self.color = color
        self.width = width

    @classmethod
    def from_string(cls, info_str):
        color, width = info_str.split(',')
        return cls(color.strip(), int(width.strip()))

# Example usage
a = Door('Brown', 80)  # Now works!
b = Door.from_string("White, 100")
print(b.color, b.width)  # Output: White 100

White 100


In [ ]:
# use case of class methode

class Donut:
    def __init__(self, falour, size):  # Fixed: Double underscores
        self.falour = falour
        self.size = size

        

In [68]:
# how many object created 

class Car:
    car_count=0
    def __init__(self):
        Car.car_count += 1
    @classmethod
    def classcount(cls):
        return cls.car_count

c1=Car()
c2=Car()
c3=Car()
c4=Car()

print(Car.classcount())        

4


4


In [72]:
class Singleton:
    _instance = None  # Class variable to store the single instance

    def __new__(cls, *args, **kwargs):
        if cls._instance is not None:
            raise RuntimeError("A second instance of Singleton is not allowed!")
        cls._instance = super().__new__(cls)  # Fixed: Correct method and variable name
        return cls._instance

    def __init__(self, value):
        self.value = value

# Usage
first = Singleton("First instance")  # Works
print(first.value)  # Output: First instance

try:
    second = Singleton("Second instance")  # Raises error (as expected)
except RuntimeError as e:
    print(e)  # Output: A second instance of Singleton is not allowed!

First instance
A second instance of Singleton is not allowed!


In [73]:
class UpperStr(str):
    def __new__(cls,content):
        obj=super().__new__(cls,content.upper())
        return obj
    

s=UpperStr("heelo")    
print(s)

HEELO
