# Today we learn about Python

In [3]:
print(True)
print(False)
x=None
print(x)

print(...)

def add(a, b):
    return NotImplemented

print(__debug__)    



True
False
None
Ellipsis
True


In [ ]:
# whata is ellipsis?
# used for placeholders, e.g. in function definitions or type hints ,,, advanced slicing

# mean something is missing so we used ... here i used python ellipsis object

In [ ]:
import numpy as np
arr=np.arange(27).reshape(3,3,3)
print(arr)
print("-----------------------------")




[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]
-----------------------------


In [11]:
print(arr[:,:,0],'\n')
print(arr[...,0],'\n')  # using ellipsis to select all elements in the last dimension
print(arr[...,1],'\n')  # using ellipsis to select all elements in the last dimension

[[ 0  3  6]
 [ 9 12 15]
 [18 21 24]] 

[[ 0  3  6]
 [ 9 12 15]
 [18 21 24]] 

[[ 1  4  7]
 [10 13 16]
 [19 22 25]] 



In [18]:
print(arr,'\n\n')
# filter only first row of each one
print('======================================')
print(arr[:, 0, ...])


[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]] 


[[ 0  1  2]
 [ 9 10 11]
 [18 19 20]]


In [19]:
print(arr[0,...],'\n')  # using ellipsis to select all elements in the last dimension

[[0 1 2]
 [3 4 5]
 [6 7 8]] 



In [20]:
print(...)

Ellipsis


In [30]:
# concept of type Hint


def greet(name: str) -> str:
    return f"Hello, {name}!"


print(greet("Adeel"))
print(greet(123))


def add_numbers(a: int, b: int) -> int:
    return a + b

print(add_numbers(5, 10))
print(add_numbers("Num", "Adeel"))  



Hello, Adeel!
Hello, 123!
15
NumAdeel


In [ ]:
#  use ellipse in callable 

from typing import Callable
def call_back_fun(f: Callable[...,int]):
    result=f('hello',7,False)
    print('call_back_fun print : ',result)

def sample_function(a,b,c):
    return 42    

a=call_back_fun(sample_function)
print("what a is print",a)


call_back_fun print :  42
None


In [ ]:
# use ellipsis in get item method of a class
class MyClass:
    def __getitem__(self, item):
        if item is ...:  # Check for ellipsis
            return "You used ellipsis!"
        return f"You accessed item: {item}"
    
    

In [42]:
# not implemented example
class MyNotImplementedClass:
    def my_method(self):
        return NotImplemented



# Example of NotImplemented in equality checks


class A:
    def __eq__(self,other):
        if isinstance(other, B):
            return False
        return NotImplemented

class B:
    def __eq__(self, other):
        if isinstance(other, A):
            return True
        return NotImplemented

a=A()
b=B()
print(a == b)  # This will return NotImplemented


False


In [40]:
print(b == a)  # This will return False, as B's __eq__ method returns False for A        

False


In [43]:

class Teacher:
    def __eq__(self, other):
        if isinstance(other, Student):
            return False  # Teachers are not equal to students
        return NotImplemented

class Student:
    def __eq__(self, other):
        if isinstance(other, Teacher):
            return True  # Students respect teachers and say they're equal 😄
        return NotImplemented

t = Teacher()
s = Student()

print(t == s)  # Output: False
print(s == t)  # Output: True


False
True


In [44]:
class A:
    def __eq__(self, other):
        return NotImplemented  

class B:
    def __eq__(self, other):
        if isinstance(other, A):
            return True  
        return NotImplemented

a = A()
b = B()

print(a == b)  # Output: True


True


In [45]:
class A:
    def __eq__(self, other):
        return NotImplemented  

class B:
    def __eq__(self, other):
        return NotImplemented  

a = A()
b = B()

print(a == b)  # Output: False


False


In [ ]:
class A:
    def __eq__(self, other):
        if isinstance(other, B):
            return False  
        return NotImplemented

class B:
    def __eq__(self, other):
        return NotImplemented  

a = A()
b = B()

print(a == b)  # Output: False


False
